config/routes.rb
Captar::Application.routes.draw do
  resources :projects, except: [:index, :show] do
    resources :stories, except: [:index] do
      member do
        put 'want'
        put 'despise'
      end
    end
  end
  get '/projects/:project_id' => 'stories#index', as: 'project'

  root to: 'pages#show', id: 'home'

end

app/models/project.rb
class Project
  include Mongoid::Document

  field :title,  type: String
  field :points, type: Integer
  embeds_many :stories

  delegate :despised, to: :stories, prefix: true
  delegate :ordered,  to: :stories, prefix: true
  delegate :wanted,   to: :stories, prefix: true

  validates :title, :points, presence: true
  validates :points, numericality: { greater_than: 0 }
end

app/models/story.rb
# encoding: UTF-8
class Story
  include Mongoid::Document

  field :title,       type: String
  field :description, type: String
  field :points,      type: Integer
  field :importance,  type: Integer
  field :wanted,      type: Boolean, default: false
  embedded_in :project

  POINTS = [1, 2, 3, 5, 8, 13, 20]

  validates :title, presence: true
  validates :points, inclusion: POINTS
  validates :importance, inclusion: [1, 2, 3]

  def self.ordered(collection = self.all)
    collection.to_a.sort { |a, b| (a.weight <=> b.weight) }
  end

  def self.wanted
    where(wanted: true).ordered
  end

  def self.despised
    where(wanted: false).ordered
  end

  def weight
    raise Exception if importance.blank? || points.blank?
    (importance + points) / 2.0
  end

  def want!
    self.wanted = true
    save
  end

  def despise!
    self.wanted = false
    save
  end

  def to_s
    if valid?
      "(#{points} pontos, #{importance_as_string}) #{title}"
    else
      '- incompleta -'
    end
  end

  private

  def importance_as_string
    case importance
    when 1 then 'alta'
    when 2 then 'média'
    when 3 then 'baixa'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < HighVoltage::PagesController
  layout :layout_for_page

  protected

  def layout_for_page
    case params[:id]
    when 'home'
      'home'
    else
      'application'
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  helper_method :parent, :resource

  # GET /stories
  def index
    @project          = Project.find(params[:project_id])
    @despised_stories = @project.stories_despised
    @wanted_stories   = @project.stories_wanted
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: resource }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = parent.stories.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    resource
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = parent.stories.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to [parent], notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    resource

    respond_to do |format|
      if resource.update_attributes(params[:story])
        format.html { redirect_to [parent, resource], notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    resource.destroy

    respond_to do |format|
      format.html { redirect_to parent }
      format.json { head :no_content }
    end
  end

  def want
    story = parent.stories.find(params[:id])
    story.want!
    redirect_to parent
  end

  def despise
    story = parent.stories.find(params[:id])
    story.despise!
    redirect_to parent
  end

  private

  def parent
    @project ||= Project.find(params[:project_id])
  end

  def resource
    @story ||= parent.stories.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_title
    (@project.nil? || @project.title.nil?) ? 'Captar' : @project.title
  end

  def project_link
    params[:project_id].nil? ? root_url : project_url(params[:project_id])
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def story(story = @story)
    StoriesExhibit.new(story)
  end
end

app/views/layouts/_head.html.slim
head
  meta[charset="utf-8"]
  meta[http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"]
  meta[name="viewport" content="width=device-width, initial-scale=1.0"]
  /[if lt IE 9]
    = javascript_include_tag "//html5shim.googlecode.com/svn/trunk/html5.js"
    meta[http-equiv="Content-Type" content="text/html;charset=utf-8"]
  title = content_for?(:title) ? yield(:title) : "Captar"
  = csrf_meta_tags
  = stylesheet_link_tag "application", media: "all"
  link[href="/favicon.ico" rel="shortcut icon"]
  / link href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144"
  / link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114"
  / link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72"
  / link href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  = render "layouts/head"

  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to project_title, project_link, class: 'brand'
          - if content_for?(:navbar)
            a.btn.btn-navbar[data-target=".nav-collapse" data-toggle="collapse"]
              span.icon-bar
              span.icon-bar
              span.icon-bar
            .nav-collapse
              .pull-right
                = yield(:navbar)

    .container
      .content
        .row
          .span12
            = yield

    footer#footer
      .container
        p
          = link_to 'Captar', root_path
          |  &copy; Caixa de Ideias 2013
    = javascript_include_tag "application"

app/views/layouts/home.html.slim
doctype html
html lang="en"
  = render "layouts/head"

  body#home
    = link_to 'https://github.com/caixadeideias/captar' do
      = image_tag '//s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png', alt: 'Fork me on GitHub', id: 'github-ribbon'
    = yield

    = javascript_include_tag "application"

app/views/pages/home.html.slim
section.banner
  .container
    .row
      .logo
        = image_tag 'logo.png', size: '203x61'
      .hero-unit
        h1.text-center = t('.slogan')
        p.text-center = t('.pitch')

  .cta
    .container
      .row
        p.text-center
          = link_to t('.start_project'), new_project_path, class: 'btn btn-large btn-inverse'

app/views/projects/_form.html.slim
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      h2 = t('projects.form.errors', count: @project.errors.count)
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title, autofocus: true
  .field
    = f.label :points
    = f.number_field :points, min: 1
  .actions = f.submit nil, class: 'btn btn-success'

app/views/projects/edit.html.slim
h1 = t('.title', name: @project.title)

== render 'form'

.row
  = link_to t('edit.more_info'), @project, class: 'btn span2'

app/views/projects/new.html.slim
h1 = t('.title')

== render 'form'

= link_to t('actions.back'), :back

app/views/stories/_form.html.slim
= form_for [parent, resource] do |f|
  - if resource.errors.any?
    #error_explanation
      h2 = t('.errors', count: resource.errors.count)
      ul
        - resource.errors.full_messages.each do |msg|
          li = msg
  .field
    = f.label :title
    br
    = f.text_field :title, autofocus: true
  .field
    = f.label :points
    br
    = f.select :points, Story::POINTS
  .field
    = f.label :importance
    br
    = f.select :importance, [%w(Alta 1), %w(Intermediária 2), %w(Baixa 3)]
  .field
    = f.label :description
    br
    = f.text_area :description
  .actions
    = f.submit nil, class: 'btn btn-success'

app/views/stories/_modal.html.slim
#doneModal.modal.hide.fade[tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"]
  .modal-header
    button.close[type="button" data-dismiss="modal" aria-hidden="true"] &times;
    h3#myModalLabel Feitoria!
  .modal-body
    p Para que outras pessoas tenham acesso as funcionalidades descritas aqui, envie a elas a URL:
    .well.text-center
      = request.url
  .modal-footer
    button.btn[data-dismiss="modal" aria-hidden="true"] Fechar

app/views/stories/edit.html.slim
h1 = t('edit.title', name: resource.title)

= render 'form'

.row
  = link_to t('stories.back_to_project'), project_path(parent), class: 'btn span2'
  = link_to t('edit.more_info'), [parent, resource], class: 'btn span2'
  = link_to t('actions.delete'), [parent, resource], method: :delete, data: { confirm: t('actions.are_you_sure') }, class: 'btn btn-danger span2'

app/views/stories/index.html.slim
= render 'modal'
- content_for(:navbar) do
  span#remaining_points = StoriesExhibit.remaining_points(@wanted_stories, parent.points)
  = link_to 'Adicionar funcionalidade', new_project_story_path(parent), class: 'btn'
  = link_to 'Feitoria!', '#doneModal', class: 'btn btn-success pull-right', "data-toggle" => "modal"
.row
  .span6
    h1 Funcionalidades que ficam de fora
    table.table
      thead
        tr
          th Descrição
          th
          th
          th
          th
      tbody
        - @despised_stories.each do |s|
          - resource = story(s)
          tr
            td
              span = image_tag 'info-icon.png', size: '22x22', 'data-title' => resource.title, 'data-content' => resource.description, class: 'info-icon'
              span = link_to resource.to_s, [parent, resource]
            td = link_to t('.want'), want_project_story_path(parent, resource), method: :put, class: 'btn btn-mini btn-success'
            td = link_to t('actions.edit'), edit_project_story_path(parent, resource), class: 'btn btn-mini'

  .span6
    h1 Funcionalidades que serão feitas
    table.table
      thead
        tr
          th Descrição
          th
          th
          th
          th
      tbody
        - @wanted_stories.each do |s|
          - resource = story(s)
          tr
            td
              span = image_tag 'info-icon.png', size: '22x22', 'data-title' => resource.title, 'data-content' => resource.description, class: 'info-icon'
              span = link_to resource.to_s, [parent, resource]
            td = link_to t('.dont_want'), despise_project_story_path(parent, resource), method: :put, class: 'btn btn-mini btn-danger'
            td = link_to t('actions.edit'), edit_project_story_path(parent, resource), class: 'btn btn-mini'

app/views/stories/new.html.slim
h1 = t('.title')

= render 'form'

= link_to t('actions.back'), :back

app/views/stories/show.html.slim
p#notice = notice
p
  b = "#{t('mongoid.attributes.story.title')}: "
  = resource.title
p
  b = "#{t('mongoid.attributes.story.description')}: "
  = resource.description
p
p
  b = "#{t('mongoid.attributes.story.points')}: "
  = resource.points
p
  b = "#{t('mongoid.attributes.story.importance')}: "
  = resource.importance

.row
  = link_to t('stories.back_to_project'), project_path(parent), class: "btn span2"
  = link_to t('actions.edit'), edit_project_story_path(parent, resource), class: 'btn span2'
  = link_to t('actions.delete'), [parent, resource], method: :delete, data: { confirm: t('actions.are_you_sure') }, class: 'btn btn-danger span2'